services:
  nginx:
    depends_on:
      - php
    image: nginx:1.28.0-alpine
    container_name: fintrack-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - .:/var/www/html
    networks:
      - app-network

  php:
    build: docker/php
    container_name: fintrack-php
    depends_on:
      - mysql
    restart: unless-stopped
    env_file: docker/local.env
    ports:
      - "9000:9000"
    volumes:
      - ./docker/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - .:/var/www/html
    networks:
      - app-network

  mysql:
    image: mysql:8.4
    container_name: fintrack-mysql
    restart: unless-stopped
    env_file: docker/local.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    container_name: fintrack-phpmyadmin
    restart: unless-stopped
    env_file: docker/local.env
    ports:
      - "3307:80"
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
